// Generated by CoffeeScript 1.9.3
(function() {
    var Music, func;

    Music = new __BaseModel('music_formid');

    Music.sync();

    func = new __BaseFunction(Music);

    module.exports = func;

}).call(this);
