// Generated by CoffeeScript 1.9.3
(function() {
  var Music, func;

  Music = new __BaseModel('music_cat_music');

  Music.sync();

  func = new __BaseFunction(Music);
  func.deleteByCondition = function(condition,callback){
      return this.model.find({
          where: condition
      }).success(function(m) {
          if (!m) {
              return callback(new Error('不存在'));
          } else {
              return m.destroy().success(function() {
                  return callback && callback(null, m);
              }).error(function(error) {
                  return callback && callback(error);
              });
          }
      }).error(function(error) {
          return callback && callback(error);
      });
  }
  module.exports = func;

}).call(this);
