// Generated by CoffeeScript 1.9.3
(function() {
    module.exports = function(req, res, next) {
        if(req.header('user-agent').indexOf('%E7%9D%A1%E5%89%8D%E6%95%85%E4%BA%8B%E4%B9%A6')===-1){
            // 如果不是app
            if(req.header('referer').indexOf('www.html-js.com')===-1){
                return next('系统错误');
            }else{
                return next();
            }
        }else{
            return next();
        }

    };

}).call(this);
