// Generated by CoffeeScript 1.9.3
(function() {
    module.exports = {
        id: {
            type: "int",
            autoIncrement: true,
            primaryKey: true
        },
        cat_id : "int",
        music_id : "int"
    };

}).call(this);
