// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    user_id: "varchar(40)",
    zip: "varchar(500)",
    story_id:'int'
  };

}).call(this);
