// Generated by CoffeeScript 1.9.3
(function() {
    module.exports = {
        id: {
            type: "int",
            autoIncrement: true,
            primaryKey: true
        },
        user_id: "varchar(40)",
        story_id: "int",
        text: "text"
    };

}).call(this);
