// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    user_id: "varchar(40)",
    title: "varchar(100)",
    content: "varchar(1000)",
    link: "varchar(1000)",
    story_id:'int',
    click_count:'int',
    type:{
      type: 'int',
      defaultValue:0
    } //0 默认 1 故事更新 2 绘本更新 3 活动通知
  };

}).call(this);
