// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    uuid: "varchar(40)",
    desc: "text",
    has_share:{
        type: "int",
        defaultValue: 0
    },
    audio: "varchar(500)",
    cover: "varchar(500)",
    title: "varchar(200)",
    author: "varchar(100)",
    index: "int",
    duration:'int',
    visit_count: {
      type: "int",
      defaultValue: 1
    },
    fav_count: {
      type: "int",
      defaultValue: 1
    },
    play_count: {
      type: "int",
      defaultValue: 1
    },
    zip: "varchar(500)",
    qr: "varchar(500)",
    isbn:"varchar(20)",
    zip_time:"DATETIME",

    book_author:"varchar(200)", //书的作者
    buy_price:"int", //购买价格
    buy_id:"varchar(100)", // 商品对应的苹果内购id
    store_has:{
      type: "int",
      defaultValue: 0
    }, // 店内是否有此书
  };

}).call(this);
