// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    user_id: "varchar(40)",
    keyword: "varchar(100)",
    result_count:"int",
    search_count:"int"
  };

}).call(this);
