// Generated by CoffeeScript 1.9.3
(function() {
    module.exports = {
        id: {
            type: "int",
            autoIncrement: true,
            primaryKey: true
        },
        phone: "varchar(100)",
        uuid: "varchar(100)",
        name: "varchar(100)",
        password:"varchar(100)"
    };

}).call(this);
