// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    user_id: "varchar(40)",
    music_id: "int",
    is_down: {
      default: 0,
      type: 'int'
    }
  };

}).call(this);
