// Generated by CoffeeScript 1.9.3
(function() {
    module.exports = {
        id: {
            type: "int",
            autoIncrement: true,
            primaryKey: true
        },
        openId: "varchar(100)",
        unionId: "varchar(100)",
        nickName: "varchar(100)",
        province:"varchar(100)",
        country:"varchar(100)",
        city:"varchar(100)",
        avatarUrl:"varchar(100)",
        gender:"varchar(100)"
    };

}).call(this);
